# Generated by Django 3.1.7 on 2021-02-25 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cate', models.CharField(help_text='Enter the category of product', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='sub_cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_cate', models.CharField(help_text='Enter the sub category of the product', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(help_text='Enter the product name', max_length=150)),
                ('desc', models.TextField(help_text='Enter the description of the product')),
                ('price', models.IntegerField(help_text='Enter the price of the product')),
                ('product_img', models.ImageField(help_text='Upload the image or enter the url', upload_to='product_img')),
                ('pub_date', models.DateField(auto_now_add=True)),
                ('product_cate', models.ForeignKey(help_text='Select the product category', on_delete=django.db.models.deletion.CASCADE, to='index.category')),
                ('product_subcate', models.ForeignKey(help_text='Select the sub product category', on_delete=django.db.models.deletion.CASCADE, to='index.sub_cat')),
                ('user', models.ForeignKey(help_text='Product added by ?', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
