# Generated by Django 3.1.7 on 2021-02-25 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_img',
            field=models.URLField(help_text='Upload the image or enter the url'),
        ),
    ]
